echo to stderr & better file discovery

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,29 +1,43 @@
 #!/bin/bash
 
 FILE_DIR="$(pwd)/files"
-PROVIDED_FILENAMES="$(find $FILE_DIR/* -printf '%f ')"
 
-for FILE in $PROVIDED_FILENAMES; do
-    if [ ! -f "$FILE_DIR/$FILE" ]; then
-        echo "internal error: Provided file $FILE does not exist."
+function find-and-echo-provided-file-basenames {
+    if [ -z "$FILE_DIR" ]; then
+        echo "No file directory specified" >&2
         exit 1
     fi
-done
+    echo "Looking for files in $FILE_DIR" >&2
+    local PROVIDED_FILENAMES="$(find $FILE_DIR/*)"
+    for FILE in $PROVIDED_FILENAMES; do
+        if [ ! -f "$FILE" ]; then
+            echo "File $FILE does not exist" >&2
+            exit 1
+        fi
+        echo "$(basename $FILE)"
+    done
+}
+
+PROVIDED_FILENAMES="$(find-and-echo-provided-file-basenames)"
+
+echo "Provided files:" >&2
+echo "$PROVIDED_FILENAMES" >&2
+
 
 if [ -z "$INSTALL_PREFIX" ]; then
     INSTALL_PREFIX="$HOME"
 fi
 
-echo "info: INSTALL_PREFIX is: $INSTALL_PREFIX"
+echo "info: INSTALL_PREFIX is: $INSTALL_PREFIX" >&2
 
 if [ -z "$BACKUP_DIR" ]; then
     BACKUP_DIR="$INSTALL_PREFIX/.shell-backup-dir"
 fi
 
-echo "info: BACKUP_DIR is: $BACKUP_DIR"
+echo "info: BACKUP_DIR is: $BACKUP_DIR" >&2
 
 function restore-backed-up-files-and-delete-links {
-    echo "info: Restoring backed up files in $BACKUP_DIR to $INSTALL_PREFIX"
+    echo "info: Restoring backed up files in $BACKUP_DIR to $INSTALL_PREFIX" >&2
     for FILE in $PROVIDED_FILENAMES; do
         local LINK="$INSTALL_PREFIX/.$FILE"
         local BACKUP="$BACKUP_DIR/$FILE"
@@ -31,11 +45,11 @@ function restore-backed-up-files-and-delete-links {
             rm -v "$LINK"
         fi
         if [ ! -f "$BACKUP" ]; then
-            echo "info: No backup for $FILE found, skipping"
+            echo "info: No backup for $FILE found, skipping" >&2
             continue
         fi
         if [ -e "$LINK" ]; then
-            echo "error: Unable to restore backed up file '$FILE' because the original location '$LINK' is still in use."
+            echo "error: Unable to restore backed up file '$FILE' because the original location '$LINK' is still in use." >&2
         else
             mv -v "$BACKUP" "$LINK"
         fi
@@ -43,19 +57,19 @@ function restore-backed-up-files-and-delete-links {
     if [  -d "$BACKUP_DIR" ]; then
         rmdir -v "$BACKUP_DIR"
         if [ -e "$BACKUP_DIR" ]; then
-            echo "error: Unable to remove old backup dir '$BACKUP_DIR'. Remove manually."
+            echo "error: Unable to remove old backup dir '$BACKUP_DIR'. Remove manually." >&2
         fi
     fi
 }
 
 function do-backup-files {
-    echo "info: Backing up files in $INSTALL_PREFIX at backup location: $BACKUP_DIR"
+    echo "info: Backing up files in $INSTALL_PREFIX at backup location: $BACKUP_DIR" >&2
     if [ -d "$BACKUP_DIR" ]; then
-        echo "error: The backup directory must not exist prior to backing up files. Choose an empty one or delete the current one: $BACKUP_DIR"
+        echo "error: The backup directory must not exist prior to backing up files. Choose an empty one or delete the current one: $BACKUP_DIR" >&2
         exit 1
     fi
     if ! mkdir -p "$BACKUP_DIR"; then
-        echo "error: Failed to create empty backup directory: $BACKUP_DIR"
+        echo "error: Failed to create empty backup directory: $BACKUP_DIR" >&2
     fi
     local DID_DO_RENAME=false
     for FILE in $PROVIDED_FILENAMES; do
@@ -65,26 +79,26 @@ function do-backup-files {
             mv -v "$ORIGINAL" "$BACKUP"
             local DID_DO_RENAME=true
         else
-            echo "info: $FILE does not exist: Skipping backup"
+            echo "info: $FILE does not exist: Skipping backup" >&2
         fi
     done
     if [ "$DID_DO_RENAME" = false ]; then
-        echo "info: Deleting backup dir because no backups have been made."
+        echo "info: Deleting backup dir because no backups have been made." >&2
         rmdir -v "$BACKUP_DIR"
     fi
 }
 
 function link-provided-files {
-    echo "info: Linking provided files to $INSTALL_PREFIX"
+    echo "info: Linking provided files to $INSTALL_PREFIX" >&2
     for FILE in $PROVIDED_FILENAMES; do
         local LINK="$INSTALL_PREFIX/.$FILE"
         local SOURCE="$FILE_DIR/$FILE"
         if [ ! -f "$SOURCE" ]; then
-            echo "error: Provided file $FILE not found in source repo."
+            echo "error: Provided file $FILE not found in source repo." >&2
             continue
         fi
         if [ -e "$LINK" ]; then
-            echo "error: Unable to link '$FILE' because the target location '$LINK' is still in use."
+            echo "error: Unable to link '$FILE' because the target location '$LINK' is still in use." >&2
             continue
         fi
         ln -vs "$SOURCE" "$LINK"
