echo all to stderr

diff --git a/files/profile b/files/profile
--- a/files/profile
+++ b/files/profile
@@ -35,7 +35,7 @@ export LME="lme201.cs.fau.de"
 if [ -n "$BASH_VERSION" ]; then
     # include .bashrc if it exists
     if [ -f "$HOME/.bashrc" ]; then
-        echo "profile sourcing bashrc: $HOME/.bashrc"
+        echo "profile sourcing bashrc: $HOME/.bashrc" >&2
         . "$HOME/.bashrc"
     fi
 fi
@@ -43,9 +43,9 @@ fi
 # Set the npm package install dir
 if command -v npm &> /dev/null; then
     if [ -z "$LOCAL" ]; then
-        echo "error: npm is installed but variable LOCAL is not set: Unable to set npm install dir."
+        echo "error: npm is installed but variable LOCAL is not set: Unable to set npm install dir." >&2
     elif [ ! "$(npm config get prefix)" == "$LOCAL" ]; then
-        echo "npm is installed: Setting install directory to $LOCAL"
+        echo "npm is installed: Setting install directory to $LOCAL" >&2
         npm config set prefix "$LOCAL"
     fi
 fi
